import {Component, OnInit,AfterViewInit, ViewChild} from '@angular/core';
import { AngularFire, FirebaseListObservable } from 'angularfire2';
//import { GoogleMapsAPIWrapper, MarkerManager, SebmGoogleMapMarker } from 'angular2-google-maps/core';

@Component({
  selector: 'app-my-boulodromes',
  templateUrl: './my-boulodromes.component.html',
  styleUrls: ['./my-boulodromes.component.scss']

})
export class MyBoulodromesComponent implements OnInit, AfterViewInit {

  public boulodromes: FirebaseListObservable<any[]>;
  public boulodromeIsSelected:boolean=false;
  public boulodrome: Object;
  public index:string;
  public title: string='';
  public ville: string='';
  public departement: number;
  public secteur: string='';
  public type: string='';
  public adresse: string='';
  public latitude: number;
  public longitude: number;
  public nbTerrains: number;
  public couvert:boolean=false;

  public lat: number = 43.3;
  public lng: number = 1.4;

  public showMap:boolean = false;

  markers: Array<Object> = [
    {
    adresse : "Boulodrome Municipal",
    couvert : false,
    departement : 31,
    id : "1",
    id_secteur : "8",
    latitude : 43.32077,
    longitude : 1.5895,
    nbTerrains : 10,
    nom : "Aignes",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Aignes"
  }, {
    couvert : false,
    departement : 31,
    id : "2",
    id_secteur : "3",
    latitude : 43.35463,
    longitude : 0.81742,
    nom : "Anan",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Anan"
  }, {
    couvert : false,
    departement : 31,
    id : "3",
    id_secteur : "3",
    latitude : "43.00968",
    longitude : "0.79648",
    nom : "Boule Du Cagire",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Aspet"
  }, {
    couvert : false,
    departement : 31,
    id : "4",
    id_secteur : "4",
    latitude : "43.66948",
    longitude : "1.4295",
    nom : "Aucamville",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Aucamville"
  }, {
    adresse : "Le Village",
    couvert : false,
    departement : 31,
    id : "5",
    id_secteur : "8",
    latitude : "43.48155",
    longitude : "1.45226",
    nom : "Aureville",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Aureville"
  }, {
    "abbrev" : "AURIAC",
    adresse : "Avenue de la Gare",
    couvert : false,
    departement : 31,
    id : "6",
    id_secteur : "8",
    latitude : "43.52493",
    longitude : "1.82606",
    nom : "Auriac Sur Vendinelle",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Auriac Sur Vendinelle"
  }, {
    couvert : false,
    departement : 31,
    id : "7",
    id_secteur : "3",
    latitude : "43.21626",
    longitude : "0.88269",
    nom : "Aurignac",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Aurignac"
  }, {
    couvert : false,
    departement : 31,
    id : "8",
    id_secteur : "7",
    latitude : "43.68031",
    longitude : "1.31832",
    nom : "Aussonne",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Aussonne"
  }, {
    adresse : "6 route de Toulouse",
    couvert : false,
    departement : 31,
    id : "9",
    id_secteur : "1",
    latitude : "43.34761",
    longitude : "1.47405",
    nom : "Auterive",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Auterive"
  }, {
    adresse : "6 Chemin des Coteaux",
    couvert : false,
    departement : 31,
    id : "10",
    id_secteur : "8",
    latitude : "43.52909",
    longitude : "1.47736",
    nom : "Auzeville",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Auzeville Tolosane"
  }, {
    adresse : "Terrain des Sports",
    couvert : false,
    departement : 31,
    id : "11",
    id_secteur : "8",
    latitude : "43.43677",
    longitude : "1.59911",
    nom : "Ayguesvives",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Ayguesvives"
  }, {
    couvert : false,
    departement : 31,
    id : "12",
    id_secteur : "4",
    latitude : "43.72582",
    longitude : "1.67263",
    nom : "Azas",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Azas"
  }, {
    "abbrev" : "Montauban De Luchon",
    couvert : false,
    departement : 31,
    id : "13",
    id_secteur : "3",
    latitude : "42.78972",
    longitude : "0.5972",
    nom : "Luchon",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Bagneres De Luchon"
  }, {
    couvert : false,
    departement : 31,
    id : "15",
    id_secteur : "2",
    latitude : "43.59757",
    longitude : "1.50718",
    nom : "Lasbordes",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Balma"
  }, {
    "abbrev" : "PIN-BALMA",
    adresse : "4 rue des Jardins",
    couvert : true,
    departement : 31,
    id : "14",
    id_secteur : "8",
    latitude : "43.61228",
    longitude : "1.48583",
    nom : "Balma",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Balma"
  }, {
    couvert : false,
    departement : 31,
    id : "16",
    id_secteur : "3",
    latitude : "43.03352",
    longitude : "0.62658",
    nom : "Barbazan",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Barbazan"
  }, {
    adresse : "6 Place de la Bascule",
    couvert : false,
    departement : 31,
    id : "17",
    id_secteur : "8",
    latitude : "43.45469",
    longitude : "1.61298",
    nom : "Baziege",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Baziege"
  }, {
    couvert : false,
    departement : 31,
    id : "18",
    id_secteur : "4",
    latitude : "43.73516",
    longitude : "1.51639",
    nom : "Bazus",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Bazus"
  }, {
    "abbrev" : "Beaumont",
    adresse : "Place Clément Ader",
    couvert : false,
    departement : 31,
    id : "19",
    id_secteur : "6",
    latitude : "43.38209",
    longitude : "1.35463",
    nom : "Beaumont Sur Leze",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Beaumont Sur Leze"
  }, {
    couvert : false,
    departement : 31,
    id : "20",
    id_secteur : "4",
    latitude : "43.64618",
    longitude : "1.55279",
    nom : "Beaupuy",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Beaupuy"
  }, {
    couvert : false,
    departement : 31,
    id : "21",
    id_secteur : "7",
    latitude : "43.66015",
    longitude : "1.38234",
    nom : "Beauzelle",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Beauzelle"
  }, {
    adresse : "Place de la Mairie",
    couvert : false,
    departement : 31,
    id : "22",
    id_secteur : "1",
    latitude : "43.37936",
    longitude : "1.17588",
    nom : "Berat",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Berat"
  }, {
    couvert : false,
    departement : 31,
    id : "24",
    id_secteur : "4",
    latitude : "43.79623",
    longitude : "1.60546",
    nom : "Boule Bessieraine",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Bessieres"
  }, {
    couvert : false,
    departement : 31,
    id : "23",
    id_secteur : "4",
    latitude : "43.79609",
    longitude : "1.60797",
    nom : "Bessieres CPB",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Bessieres"
  }, {
    "abbrev" : "BLAGNAC-PARC",
    couvert : false,
    departement : 31,
    id : "26",
    id_secteur : "7",
    latitude : "43.64126",
    longitude : "1.38321",
    nom : "Blagnac Parc",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Blagnac"
  }, {
    couvert : false,
    departement : 31,
    id : "25",
    id_secteur : "7",
    latitude : "43.636",
    longitude : "1.4016",
    nom : "Blagnac Ramier",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Blagnac"
  }, {
    couvert : false,
    departement : 31,
    id : "27",
    id_secteur : "4",
    latitude : "43.78122",
    longitude : "1.40561",
    nom : "Bouloc",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Bouloc"
  }, {
    "abbrev" : "Boulogne",
    couvert : false,
    departement : 31,
    id : "28",
    id_secteur : "3",
    latitude : "43.28833",
    longitude : "0.64703",
    nom : "Boulogne Sur Gesse",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Boulogne Sur Gesse"
  }, {
    "abbrev" : "Bourg Saint-Bernard",
    adresse : "Place du Pradal",
    couvert : false,
    departement : 31,
    id : "29",
    id_secteur : "8",
    latitude : "43.60012",
    longitude : "1.71281",
    nom : "Bourg-St-Bernard",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Bourg Saint Bernard"
  }, {
    couvert : false,
    departement : 31,
    id : "30",
    id_secteur : "3",
    latitude : "43.17606",
    longitude : "0.97217",
    nom : "Boussens",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Boussens"
  }, {
    couvert : false,
    departement : 31,
    id : "31",
    id_secteur : "5",
    latitude : "43.48222",
    longitude : "1.07099",
    nom : "Boule De L'amitié Bragayrac",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Bragayrac"
  }, {
    couvert : false,
    departement : 31,
    id : "32",
    id_secteur : "5",
    latitude : "43.61643",
    longitude : "1.24044",
    nom : "Brax",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Brax"
  }, {
    couvert : false,
    departement : 31,
    id : "33",
    id_secteur : "7",
    latitude : "43.70477",
    longitude : "1.19905",
    nom : "Bretx",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Bretx"
  }, {
    couvert : false,
    departement : 31,
    id : "34",
    id_secteur : "7",
    latitude : "43.78059",
    longitude : "0.98897",
    nom : "Brignemont",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Brignemont"
  }, {
    couvert : true,
    departement : 31,
    id : "35",
    id_secteur : "4",
    latitude : "43.72753",
    longitude : "1.41474",
    nom : "Bruguieres PC",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Bruguieres"
  }, {
    couvert : false,
    departement : 31,
    id : "36",
    id_secteur : "4",
    latitude : "43.77784",
    longitude : "1.63602",
    nom : "Buzet",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Buzet Sur Tarn"
  }, {
    couvert : false,
    departement : 31,
    id : "37",
    id_secteur : "7",
    latitude : "43.72308",
    longitude : "1.04675",
    nom : "Cadours",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Cadours"
  }, {
    couvert : false,
    departement : 31,
    id : "38",
    id_secteur : "8",
    latitude : "43.28457",
    longitude : "1.63468",
    nom : "Calmont",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Calmont"
  }, {
    couvert : false,
    departement : 31,
    id : "39",
    id_secteur : "5",
    latitude : "43.47482",
    longitude : "1.18018",
    nom : "Cambernard",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Cambernard"
  }, {
    adresse : "Rte de Cambiac Lieu Dit l'estanquette",
    couvert : false,
    departement : 31,
    id : "40",
    id_secteur : "8",
    latitude : "43.52545",
    longitude : "1.76437",
    nom : "Caraman",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Caraman"
  }, {
    adresse : "Boulodrome Le Claous",
    couvert : true,
    departement : 31,
    id : "41",
    id_secteur : "1",
    latitude : "43.29837",
    longitude : "1.22119",
    nom : "Carbonne",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Carbonne"
  }, {
    adresse : "Av Louis Decherm",
    couvert : true,
    departement : 31,
    id : "42",
    id_secteur : "8",
    latitude : "43.52147",
    longitude : "1.49424",
    nom : "Castanet",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Castanet Tolosan"
  }, {
    "abbrev" : "Buffebiau",
    couvert : false,
    departement : 31,
    id : "44",
    id_secteur : "4",
    latitude : "43.68847",
    longitude : "1.44169",
    nom : "Ecole Petanque Buffebiau",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Castelginest"
  }, {
    couvert : false,
    departement : 31,
    id : "43",
    id_secteur : "4",
    latitude : "43.68847",
    longitude : "1.44169",
    nom : "Castelginest / Buffebiau",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Castelginest"
  }, {
    couvert : false,
    departement : 31,
    id : "45",
    id_secteur : "4",
    latitude : "43.67803",
    longitude : "1.53272",
    nom : "Castelmaurou",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Castelmaurou"
  }, {
    "abbrev" : "CASTELNAU D'ESTRET",
    couvert : false,
    departement : 31,
    id : "46",
    id_secteur : "4",
    latitude : "43.78059",
    longitude : "1.35731",
    nom : "Castelnau D'Estretefonds",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Castelnau D'Estretefonds"
  }, {
    "abbrev" : "Castelnau",
    adresse : "Place du village",
    couvert : false,
    departement : 31,
    id : "47",
    id_secteur : "1",
    latitude : "43.30622",
    longitude : "1.01687",
    nom : "Castelnau Picampau",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Castelnau Picampau"
  }, {
    adresse : "Place de la base nautique",
    couvert : false,
    departement : 31,
    id : "48",
    id_secteur : "1",
    latitude : "43.20339",
    longitude : "1.0862",
    nom : "Cazeres",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Cazeres"
  }, {
    couvert : false,
    departement : 31,
    id : "49",
    id_secteur : "4",
    latitude : "43.74936",
    longitude : "1.43223",
    nom : "Cepet",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Cepet"
  }, {
    couvert : false,
    departement : 31,
    id : "50",
    id_secteur : "3",
    latitude : "43.22479",
    longitude : "0.67393",
    nom : "Charlas",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Charlas"
  }, {
    "abbrev" : "CIER-DE-RIVIERE",
    couvert : false,
    departement : 31,
    id : "51",
    id_secteur : "3",
    latitude : "43.06741",
    longitude : "0.63356",
    nom : "Cier De Riviere",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Cier De Riviere"
  }, {
    couvert : false,
    departement : 31,
    id : "52",
    id_secteur : "3",
    latitude : "42.9165",
    longitude : "0.64127",
    nom : "Cierp Gaud La Pique",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Cierp Gaud"
  }, {
    adresse : "Rue du 19 mars",
    couvert : true,
    departement : 31,
    id : "53",
    id_secteur : "8",
    latitude : "43.31321",
    longitude : "1.52792",
    nom : "Cintegabelle",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Cintegabelle"
  }, {
    couvert : true,
    departement : 31,
    id : "54",
    id_secteur : "5",
    latitude : "43.61217",
    longitude : "1.32052",
    nom : "BJ Colomiers",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Colomiers"
  }, {
    couvert : false,
    departement : 31,
    id : "55",
    id_secteur : "7",
    latitude : "43.65193",
    longitude : "1.32685",
    nom : "Cornebarrieu",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Cornebarrieu"
  }, {
    couvert : false,
    departement : 31,
    id : "56",
    id_secteur : "7",
    latitude : "43.76044",
    longitude : "1.04332",
    nom : "Cox",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Cox"
  }, {
    "abbrev" : "JS CUGNAUX",
    couvert : false,
    departement : 31,
    id : "57",
    id_secteur : "5",
    latitude : "43.53677",
    longitude : "1.3458",
    nom : "Cugnaux",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Cugnaux"
  }, {
    couvert : false,
    departement : 31,
    id : "58",
    id_secteur : "7",
    latitude : "43.69451",
    longitude : "1.26967",
    nom : "Daux",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Daux"
  }, {
    adresse : "Place du Bicentenaire",
    couvert : false,
    departement : 31,
    id : "59",
    id_secteur : "6",
    latitude : "43.4244",
    longitude : "1.35747",
    nom : "Eaunes",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Eaunes"
  }, {
    couvert : false,
    departement : 31,
    id : "60",
    id_secteur : "3",
    latitude : "43.05222",
    longitude : "0.74231",
    nom : "Encausse",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Encausse Les Thermes"
  }, {
    adresse : "Le Village",
    couvert : false,
    departement : 31,
    id : "61",
    id_secteur : "1",
    latitude : "43.29733",
    longitude : "1.40082",
    nom : "Esperce",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Esperce"
  }, {
    couvert : false,
    departement : 31,
    id : "62",
    id_secteur : "3",
    latitude : "42.92688",
    longitude : "0.68954",
    nom : "Eup",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Eup"
  }, {
    couvert : true,
    departement : 31,
    id : "63",
    id_secteur : "4",
    latitude : "43.67657",
    longitude : "1.39223",
    nom : "Fenouillet",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Fenouillet"
  }, {
    adresse : "Place de la Mairie (Salle des Fêtes )",
    couvert : false,
    departement : 31,
    id : "64",
    id_secteur : "8",
    latitude : "43.59477",
    longitude : "1.56179",
    nom : "Flourens",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Flourens"
  }, {
    couvert : false,
    departement : 31,
    id : "65",
    id_secteur : "4",
    latitude : "43.68289",
    longitude : "1.43506",
    nom : "Fonbeauzard PC",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Fonbeauzard"
  }, {
    couvert : false,
    departement : 31,
    id : "66",
    id_secteur : "5",
    latitude : "43.53593",
    longitude : "1.23262",
    nom : "La Boule Fonsorbaise",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Fonsorbes"
  }, {
    couvert : false,
    departement : 31,
    id : "67",
    id_secteur : "5",
    latitude : "43.55238",
    longitude : "1.19149",
    nom : "Fontenilles",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Fontenilles"
  }, {
    adresse : "Boulodrome municipal",
    couvert : false,
    departement : 31,
    id : "68",
    id_secteur : "8",
    latitude : "43.50723",
    longitude : "1.61789",
    nom : "Fourquevaux",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Fourquevaux"
  }, {
    couvert : false,
    departement : 31,
    id : "69",
    id_secteur : "4",
    latitude : "43.83852",
    longitude : "1.38999",
    nom : "Fronton",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Fronton"
  }, {
    adresse : "14 bis rue de la République",
    couvert : false,
    departement : 31,
    id : "70",
    id_secteur : "6",
    latitude : "43.51437",
    longitude : "1.32364",
    nom : "Frouzins Athletic Club Pétanque",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Frouzins"
  }, {
    couvert : false,
    departement : 31,
    id : "71",
    id_secteur : "4",
    latitude : "43.7004",
    longitude : "1.37412",
    nom : "Gagnac",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Gagnac Sur Garonne"
  }, {
    "abbrev" : "Gaillac-Toulza",
    adresse : "La Prade 31550",
    couvert : true,
    departement : 31,
    id : "72",
    id_secteur : "1",
    latitude : "43.25531",
    longitude : "1.47268",
    nom : "Gaillac Toulza",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Gaillac Toulza"
  }, {
    adresse : "Boulodrome municipal",
    couvert : false,
    departement : 31,
    id : "73",
    id_secteur : "8",
    latitude : "43.39",
    longitude : "1.68442",
    nom : "Gardouch",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Gardouch"
  }, {
    couvert : false,
    departement : 31,
    id : "74",
    id_secteur : "4",
    latitude : "43.7097",
    longitude : "1.56218",
    nom : "Garidech",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Garidech"
  }, {
    couvert : false,
    departement : 31,
    id : "75",
    id_secteur : "4",
    latitude : "43.68231",
    longitude : "1.58397",
    nom : "Gragnague",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Gragnague"
  }, {
    couvert : false,
    departement : 31,
    id : "76",
    id_secteur : "4",
    latitude : "43.72484",
    longitude : "1.43925",
    nom : "Gratentour",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Gratentour"
  }, {
    couvert : false,
    departement : 31,
    id : "77",
    id_secteur : "7",
    latitude : "43.77394",
    longitude : "1.29093",
    nom : "Grenade",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Grenade"
  }, {
    couvert : false,
    departement : 31,
    id : "78",
    id_secteur : "3",
    latitude : "43.06396",
    longitude : "0.97082",
    nom : "His",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "His"
  }, {
    adresse : "Le Village",
    couvert : false,
    departement : 31,
    id : "79",
    id_secteur : "8",
    latitude : "43.44909",
    longitude : "1.79002",
    nom : "Juzes",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Juzes"
  }, {
    "abbrev" : "L'ISLE-EN-DODON",
    couvert : false,
    departement : 31,
    id : "111",
    id_secteur : "3",
    latitude : "43.38026",
    longitude : "0.83886",
    nom : "L'Isle En Dodon",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "L'Isle En Dodon"
  }, {
    couvert : false,
    departement : 31,
    id : "114",
    id_secteur : "4",
    latitude : "43.65751",
    longitude : "1.47444",
    nom : "L'Union Petanque",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "L'Union"
  }, {
    couvert : false,
    departement : 31,
    id : "80",
    id_secteur : "4",
    latitude : "43.8092",
    longitude : "1.54338",
    nom : "La Magdelaine",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "La Magdelaine Sur Tarn"
  }, {
    "abbrev" : "La Salvetat",
    couvert : false,
    departement : 31,
    id : "81",
    id_secteur : "5",
    latitude : "43.57666",
    longitude : "1.27086",
    nom : "La Salvetat Saint Gilles",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "La Salvetat Saint Gilles"
  }, {
    "abbrev" : "Labarthe-Inard",
    couvert : false,
    departement : 31,
    id : "82",
    id_secteur : "3",
    latitude : "43.10721",
    longitude : "0.83693",
    nom : "Labarthe Inard",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Labarthe Inard"
  }, {
    "abbrev" : "Labarthe-Riviere",
    couvert : false,
    departement : 31,
    id : "83",
    id_secteur : "3",
    latitude : "43.08059",
    longitude : "0.67099",
    nom : "Labarthe Petanque Club",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Labarthe Riviere"
  }, {
    "abbrev" : "Labarthe / Leze",
    adresse : "Boul.Impasse de l'Ayguiere ",
    couvert : false,
    departement : 31,
    id : "84",
    id_secteur : "6",
    latitude : "43.45513",
    longitude : "1.3995",
    nom : "Labarthe",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Labarthe Sur Leze"
  }, {
    "abbrev" : "Labastide-Beauvoir",
    adresse : "Impasse La place",
    couvert : false,
    departement : 31,
    id : "85",
    id_secteur : "8",
    latitude : "43.48173",
    longitude : "1.66438",
    nom : "Labastide Beauvoir",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Labastide Beauvoir"
  }, {
    "abbrev" : "Labastide-Clermont",
    adresse : "Le village",
    couvert : false,
    departement : 31,
    id : "86",
    id_secteur : "1",
    latitude : "43.34856",
    longitude : "1.12229",
    nom : "Labastide Clermont",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Labastide Clermont"
  }, {
    couvert : false,
    departement : 31,
    id : "87",
    id_secteur : "4",
    latitude : "43.73966",
    longitude : "1.47072",
    nom : "Labastide Saint Sernin",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Labastide Saint Sernin"
  }, {
    adresse : "33 route principale",
    couvert : false,
    departement : 31,
    id : "88",
    id_secteur : "6",
    latitude : "43.4629",
    longitude : "1.24729",
    nom : "Labastidette",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Labastidette"
  }, {
    adresse : "Rue de la Croix Rose",
    couvert : false,
    departement : 31,
    id : "89",
    id_secteur : "8",
    latitude : "43.53068",
    longitude : "1.52891",
    nom : "Labege",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Labege"
  }, {
    adresse : "Halle de Lacroix",
    couvert : false,
    departement : 31,
    id : "90",
    id_secteur : "6",
    latitude : "43.49984",
    longitude : "1.40726",
    nom : "Lacroix Falgarde",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Lacroix Falgarde"
  }, {
    adresse : "Complexe sportif 31390",
    couvert : false,
    departement : 31,
    id : "91",
    id_secteur : "1",
    latitude : "43.29906",
    longitude : "1.16618",
    nom : "Lafitte Vigordane",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Lafitte Vigordane"
  }, {
    adresse : "Au Village",
    couvert : false,
    departement : 31,
    id : "92",
    id_secteur : "8",
    latitude : "43.34608",
    longitude : "1.71273",
    nom : "Lagarde",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Lagarde"
  }, {
    adresse : "Boul Jean Merle Parc du Château ",
    couvert : false,
    departement : 31,
    id : "93",
    id_secteur : "8",
    latitude : "43.41486",
    longitude : "1.38731",
    nom : "Lagardelle",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Lagardelle"
  }, {
    couvert : false,
    departement : 31,
    id : "94",
    id_secteur : "3",
    latitude : "43.13082",
    longitude : "0.78094",
    nom : "Landorthe",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Landorthe"
  }, {
    "abbrev" : "Lapeyrouse",
    couvert : false,
    departement : 31,
    id : "95",
    id_secteur : "4",
    latitude : "43.6912",
    longitude : "1.51722",
    nom : "Lapeyrouse Fossat",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Lapeyrouse Fossat"
  }, {
    couvert : false,
    departement : 31,
    id : "96",
    id_secteur : "7",
    latitude : "43.73876",
    longitude : "1.23354",
    nom : "Larra",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Larra"
  }, {
    couvert : true,
    departement : 31,
    id : "97",
    id_secteur : "4",
    latitude : "43.67558",
    longitude : "1.45268",
    nom : "Launaguet",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Launaguet"
  }, {
    "abbrev" : "LAVELANET CGES",
    adresse : "Place de la mairie",
    couvert : false,
    departement : 31,
    id : "98",
    id_secteur : "1",
    latitude : "43.25548",
    longitude : "1.11893",
    nom : "Lavelanet De Comminges",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Lavelanet De Comminges"
  }, {
    "abbrev" : "LAVERNOSE",
    adresse : "Complexe sportif",
    couvert : false,
    departement : 31,
    id : "99",
    id_secteur : "1",
    latitude : "43.39529",
    longitude : "1.26247",
    nom : "Lavernose Lacasse",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Lavernose Lacasse"
  }, {
    couvert : false,
    departement : 31,
    id : "100",
    id_secteur : "7",
    latitude : "43.67288",
    longitude : "1.13917",
    nom : "Castera",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Le Castera"
  }, {
    adresse : "Place du Village",
    couvert : false,
    departement : 31,
    id : "101",
    id_secteur : "6",
    latitude : "43.39601",
    longitude : "1.29556",
    nom : "Le Fauga",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Le Fauga"
  }, {
    adresse : "1 Côte de la Pobla de Ségur",
    couvert : false,
    departement : 31,
    id : "102",
    id_secteur : "1",
    latitude : "43.28282",
    longitude : "1.0646",
    nom : "Le Fousseret",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Le Fousseret"
  }, {
    couvert : false,
    departement : 31,
    id : "103",
    id_secteur : "7",
    latitude : "43.72319",
    longitude : "1.0988",
    nom : "Le Gres",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Le Gres"
  }, {
    "abbrev" : "LHERM",
    adresse : "Place de l'église 31600",
    couvert : false,
    departement : 31,
    id : "104",
    id_secteur : "1",
    latitude : "43.42965",
    longitude : "1.22391",
    nom : "Le Lherm",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Le Lherm"
  }, {
    couvert : false,
    departement : 31,
    id : "105",
    id_secteur : "5",
    latitude : "43.60084",
    longitude : "1.23258",
    nom : "Leguevin",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Leguevin"
  }, {
    couvert : false,
    departement : 31,
    id : "106",
    id_secteur : "4",
    latitude : "43.70898",
    longitude : "1.39086",
    nom : "Lespinasse",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Lespinasse"
  }, {
    "abbrev" : "LLSM",
    couvert : false,
    departement : 31,
    id : "107",
    id_secteur : "3",
    latitude : "43.12199",
    longitude : "0.9144",
    nom : "Lestelle",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Lestelle De Saint Martory"
  }, {
    couvert : false,
    departement : 31,
    id : "108",
    id_secteur : "7",
    latitude : "43.66521",
    longitude : "1.19362",
    nom : "Levignac",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Levignac"
  }, {
    couvert : false,
    departement : 31,
    id : "109",
    id_secteur : "3",
    latitude : "42.90963",
    longitude : "0.69671",
    nom : "Lez",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Lez"
  }, {
    couvert : false,
    departement : 31,
    id : "110",
    id_secteur : "3",
    latitude : "43.28502",
    longitude : "0.80917",
    nom : "Lilhac",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Lilhac"
  }, {
    "abbrev" : "LONGAGES",
    adresse : "Esplanade Besson",
    couvert : false,
    departement : 31,
    id : "112",
    id_secteur : "1",
    latitude : "43.35324",
    longitude : "1.2375",
    nom : "GEST et PET. Longages",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Longages"
  }, {
    couvert : false,
    departement : 31,
    id : "113",
    id_secteur : "3",
    latitude : "43.14755",
    longitude : "0.5738",
    nom : "Loudet",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Loudet"
  }, {
    couvert : false,
    departement : 31,
    id : "115",
    id_secteur : "4",
    latitude : "43.85969",
    longitude : "1.4821",
    nom : "Magnanac",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Magnanac (Villemur Sur Tarn)"
  }, {
    couvert : false,
    departement : 31,
    id : "116",
    id_secteur : "3",
    latitude : "43.1581",
    longitude : "0.95189",
    nom : "Mancioux",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Mancioux"
  }, {
    couvert : false,
    departement : 31,
    id : "117",
    id_secteur : "3",
    latitude : "43.0815",
    longitude : "0.951",
    nom : "Mane",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Mane"
  }, {
    adresse : "Le village",
    couvert : false,
    departement : 31,
    id : "118",
    id_secteur : "1",
    latitude : "43.31695",
    longitude : "1.24575",
    nom : "Marquefave",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Marquefave"
  }, {
    "abbrev" : "Martres-Tolosane",
    couvert : false,
    departement : 31,
    id : "119",
    id_secteur : "3",
    latitude : "43.19694",
    longitude : "1.00985",
    nom : "Martres Tolosane",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Martres Tolosane"
  }, {
    couvert : false,
    departement : 31,
    id : "120",
    id_secteur : "3",
    latitude : "43.19003",
    longitude : "1.03334",
    nom : "Mauran",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Mauran"
  }, {
    couvert : false,
    departement : 31,
    id : "121",
    id_secteur : "8",
    latitude : "43.45664",
    longitude : "1.67911",
    nom : "Mauremont",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Mauremont"
  }, {
    adresse : "Complexe sportif Place des écoles",
    couvert : false,
    departement : 31,
    id : "122",
    id_secteur : "1",
    latitude : "43.37638",
    longitude : "1.29182",
    nom : "Mauzacaise",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Mauzac"
  }, {
    couvert : false,
    departement : 31,
    id : "123",
    id_secteur : "3",
    latitude : "43.13666",
    longitude : "0.97884",
    nom : "Mazeres Cassagne",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Mazeres Sur Salat"
  }, {
    couvert : false,
    departement : 31,
    id : "124",
    id_secteur : "5",
    latitude : "43.62503",
    longitude : "1.15609",
    nom : "Merenvielle",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Merenvielle"
  }, {
    couvert : false,
    departement : 31,
    id : "125",
    id_secteur : "7",
    latitude : "43.72058",
    longitude : "1.29888",
    nom : "Merville",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Merville"
  }, {
    "abbrev" : "MIRAMONT CGES",
    couvert : false,
    departement : 31,
    id : "126",
    id_secteur : "3",
    latitude : "43.09558",
    longitude : "0.74584",
    nom : "Miramont De Comminges",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Miramont De Comminges"
  }, {
    adresse : "Place Marengaud",
    couvert : false,
    departement : 31,
    id : "127",
    id_secteur : "1",
    latitude : "43.36912",
    longitude : "1.41581",
    nom : "Boule Sportive Miremontaise",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Miremont"
  }, {
    adresse : "Foyer rural",
    couvert : false,
    departement : 31,
    id : "128",
    id_secteur : "1",
    latitude : "43.23934",
    longitude : "1.03818",
    nom : "Mondavezan",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Mondavezan"
  }, {
    couvert : false,
    departement : 31,
    id : "129",
    id_secteur : "7",
    latitude : "43.6714",
    longitude : "1.28613",
    nom : "Mondonville",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Mondonville"
  }, {
    couvert : false,
    departement : 31,
    id : "130",
    id_secteur : "7",
    latitude : "43.69173",
    longitude : "1.23083",
    nom : "Montaigut",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Montaigut Sur Save"
  }, {
    couvert : false,
    departement : 31,
    id : "131",
    id_secteur : "4",
    latitude : "43.71896",
    longitude : "1.48058",
    nom : "Montberon",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Montberon"
  }, {
    couvert : false,
    departement : 31,
    id : "132",
    id_secteur : "8",
    latitude : "43.41741",
    longitude : "1.62849",
    nom : "Montesqieu Lauragais",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Montesqieu Lauragais"
  }, {
    "abbrev" : "MONTESQUIEU",
    adresse : "Place Brin de Jonc des Moulinets",
    couvert : false,
    departement : 31,
    id : "133",
    id_secteur : "1",
    latitude : "43.20522",
    longitude : "1.22522",
    nom : "Montesquieu Volvestre",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Montesquieu Volvestre"
  }, {
    couvert : false,
    departement : 31,
    id : "134",
    id_secteur : "3",
    latitude : "43.0612",
    longitude : "0.93244",
    nom : "Montgaillard De Salies",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Montgaillard De Salies"
  }, {
    adresse : "Au Village",
    couvert : false,
    departement : 31,
    id : "135",
    id_secteur : "8",
    latitude : "43.33844",
    longitude : "1.63423",
    nom : "Montgeard",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Montgeard"
  }, {
    adresse : "Parking de l'Eglise",
    couvert : false,
    departement : 31,
    id : "136",
    id_secteur : "8",
    latitude : "43.45815",
    longitude : "1.57526",
    nom : "Montgiscard",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Montgiscard"
  }, {
    couvert : false,
    departement : 31,
    id : "137",
    id_secteur : "4",
    latitude : "43.6446",
    longitude : "1.52543",
    nom : "Montrabe",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Montrabe"
  }, {
    couvert : false,
    departement : 31,
    id : "138",
    id_secteur : "4",
    latitude : "43.71604",
    longitude : "1.59364",
    nom : "Montrastruc",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Montrastruc La Conseillere"
  }, {
    couvert : false,
    departement : 31,
    id : "139",
    id_secteur : "3",
    latitude : "43.08634",
    longitude : "0.56384",
    nom : "Montrejeau",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Montrejeau"
  }, {
    adresse : "Boul Constantini 30 Bd Aristide Briand ",
    couvert : true,
    departement : 31,
    id : "141",
    id_secteur : "6",
    latitude : "43.46368",
    longitude : "1.329",
    nom : "La Muretaine",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Muret"
  }, {
    "abbrev" : "Muret Saint-Jean",
    adresse : "12 rue Pierre Bauduc",
    couvert : true,
    departement : 31,
    id : "140",
    id_secteur : "6",
    latitude : "43.4713",
    longitude : "1.33602",
    nom : "Muret Saint Jean",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Muret"
  }, {
    adresse : "proche des terrains de tennis",
    couvert : false,
    departement : 31,
    id : "142",
    id_secteur : "8",
    latitude : "43.35829",
    longitude : "1.62205",
    nom : "Nailloux",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Nailloux"
  }, {
    adresse : "88 Route de Toulouse",
    couvert : false,
    departement : 31,
    id : "143",
    id_secteur : "1",
    latitude : "43.35257",
    longitude : "1.27341",
    nom : "Noe",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Noe"
  }, {
    adresse : "Au Village",
    couvert : false,
    departement : 31,
    id : "144",
    id_secteur : "8",
    latitude : "43.49326",
    longitude : "1.92933",
    nom : "Nogaret",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Nogaret"
  }, {
    adresse : "Boul. Jean Baptiste LAYNET ",
    couvert : false,
    departement : 31,
    id : "145",
    id_secteur : "8",
    latitude : "43.52386",
    longitude : "1.59044",
    nom : "Odars",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Odars"
  }, {
    couvert : false,
    departement : 31,
    id : "146",
    id_secteur : "4",
    latitude : "43.70723",
    longitude : "1.45995",
    nom : "Pechbonnieu",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Pechbonnieu"
  }, {
    couvert : false,
    departement : 31,
    id : "148",
    id_secteur : "4",
    latitude : "43.62325",
    longitude : "1.53061",
    nom : "Pin Balma",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Pin Balma"
  }, {
    "abbrev" : "Villatte",
    adresse : "Place saint Blaise Pins Justaret",
    couvert : false,
    departement : 31,
    id : "149",
    id_secteur : "6",
    latitude : "43.48116",
    longitude : "1.38435",
    nom : "Pins Villatte",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Pins Justaret"
  }, {
    adresse : "5 rue du Ramier",
    couvert : false,
    departement : 31,
    id : "150",
    id_secteur : "6",
    latitude : "43.51085",
    longitude : "1.38623",
    nom : "Pinsaguel",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Pinsaguel"
  }, {
    "abbrev" : "Plaisance",
    couvert : false,
    departement : 31,
    id : "151",
    id_secteur : "5",
    latitude : "43.56886",
    longitude : "1.2979",
    nom : "Plaisance Du Touch",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Plaisance Du Touch"
  }, {
    "abbrev" : "Pointis-De-Riviere",
    couvert : false,
    departement : 31,
    id : "152",
    id_secteur : "3",
    latitude : "43.09012",
    longitude : "0.62263",
    nom : "Pointis De Riviere",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Pointis De Riviere"
  }, {
    "abbrev" : "Pointis-Inard",
    couvert : true,
    departement : 31,
    id : "153",
    id_secteur : "3",
    latitude : "43.09139",
    longitude : "0.79674",
    nom : "Pointis Inard",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Pointis Inard"
  }, {
    adresse : "Rue Jane Dieulafoy",
    couvert : false,
    departement : 31,
    id : "154",
    id_secteur : "8",
    latitude : "43.48962",
    longitude : "1.51471",
    nom : "Pompertuzat",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Pompertuzat"
  }, {
    "abbrev" : "Taillebourg",
    couvert : false,
    departement : 31,
    id : "155",
    id_secteur : "3",
    latitude : "43.10886",
    longitude : "0.60072",
    nom : "Taillebourg",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Ponlat Taillebourg"
  }, {
    "abbrev" : "PORTET",
    adresse : "8 Avenue Salvador Allende",
    couvert : true,
    departement : 31,
    id : "156",
    id_secteur : "6",
    latitude : "43.53085",
    longitude : "1.41193",
    nom : "Joyeuse Petanque Portesienne",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Portet Sur Garonne"
  }, {
    adresse : "Rue Claire Fontaine",
    couvert : false,
    departement : 31,
    id : "157",
    id_secteur : "6",
    latitude : "43.54065",
    longitude : "1.40798",
    nom : "Recebedou",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Portet Sur Garonne"
  }, {
    adresse : "Place des Marroniers",
    couvert : false,
    departement : 31,
    id : "158",
    id_secteur : "6",
    latitude : "43.41651",
    longitude : "1.1719",
    nom : "Poucharramet",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Poucharramet"
  }, {
    "abbrev" : "POUY-DE- TOUGES",
    adresse : "La boule verte - Le village 31430",
    couvert : false,
    departement : 31,
    id : "159",
    id_secteur : "1",
    latitude : "43.34295",
    longitude : "1.03738",
    nom : "La Boule Verte",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Pouy De Touges"
  }, {
    couvert : false,
    departement : 31,
    id : "160",
    id_secteur : "3",
    latitude : "43.37316",
    longitude : "0.7657",
    nom : "Puymaurin",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Puymaurin"
  }, {
    "abbrev" : "FONSEGRIVES",
    adresse : "Route de la Saune",
    couvert : true,
    departement : 31,
    id : "161",
    id_secteur : "8",
    latitude : "43.58182",
    longitude : "1.5334",
    nom : "Quint Fonsegrives",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Quint Fonsegrives"
  }, {
    adresse : "Place Jean Jaures",
    couvert : false,
    departement : 31,
    id : "162",
    id_secteur : "8",
    latitude : "43.54804",
    longitude : "1.4783",
    nom : "Ramonville",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Ramonville Saint Agne"
  }, {
    adresse : "Avenue des Frères Arnaud",
    couvert : false,
    departement : 31,
    id : "163",
    id_secteur : "8",
    latitude : "43.46141",
    longitude : "1.99985",
    nom : "Revel",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Revel"
  }, {
    adresse : "Route de Saint Lys",
    couvert : false,
    departement : 31,
    id : "164",
    id_secteur : "1",
    latitude : "43.41297",
    longitude : "1.1191",
    nom : "Rieumes PCS",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Rieumes"
  }, {
    adresse : "Route de Saint-Lys",
    couvert : false,
    departement : 31,
    id : "165",
    id_secteur : "1",
    latitude : "43.41745",
    longitude : "1.12218",
    nom : "Rieumes PS",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Rieumes"
  }, {
    "abbrev" : "RIEUX",
    adresse : "Parc des Jacobins",
    couvert : false,
    departement : 31,
    id : "166",
    id_secteur : "1",
    latitude : "43.25698",
    longitude : "1.20253",
    nom : "US Riveraine",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Rieux Volvestre"
  }, {
    couvert : false,
    departement : 31,
    id : "167",
    id_secteur : "3",
    latitude : "43.16134",
    longitude : "0.97413",
    nom : "Roquefort",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Roquefort Sur Garonne"
  }, {
    "abbrev" : "Roques",
    adresse : "Place Jean Jaures",
    couvert : false,
    departement : 31,
    id : "168",
    id_secteur : "6",
    latitude : "43.50838",
    longitude : "1.37575",
    nom : "Roques",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Roques Sur Garonne"
  }, {
    adresse : "Impasse Monsegur",
    couvert : false,
    departement : 31,
    id : "169",
    id_secteur : "6",
    latitude : "43.49991",
    longitude : "1.3639",
    nom : "Roquettes",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Roquettes"
  }, {
    couvert : false,
    departement : 31,
    id : "170",
    id_secteur : "3",
    latitude : "43.053",
    longitude : "0.88234",
    nom : "Rouede Arbas",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Rouede"
  }, {
    "abbrev" : "Sabonneres acacias",
    adresse : "Bar des acacias 31370",
    couvert : false,
    departement : 31,
    id : "172",
    id_secteur : "1",
    latitude : "43.46652",
    longitude : "1.06311",
    nom : "Sabonneres Acacias",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Sabonneres"
  }, {
    adresse : "Mairie",
    couvert : false,
    departement : 31,
    id : "171",
    id_secteur : "1",
    latitude : "43.46652",
    longitude : "1.06311",
    nom : "Sabonneres",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Sabonneres"
  }, {
    couvert : false,
    departement : 31,
    id : "173",
    id_secteur : "5",
    latitude : "43.52851",
    longitude : "1.14588",
    nom : "Saiguede",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Saiguede"
  }, {
    "abbrev" : "Saint-Alban",
    couvert : true,
    departement : 31,
    id : "174",
    id_secteur : "4",
    latitude : "43.69074",
    longitude : "1.41165",
    nom : "Saint Alban",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Saint Alban"
  }, {
    "abbrev" : "SAINT-BEAT",
    couvert : false,
    departement : 31,
    id : "175",
    id_secteur : "3",
    latitude : "42.90575",
    longitude : "0.69265",
    nom : "Saint Beat",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Saint Beat"
  }, {
    "abbrev" : "SAINT-CEZERT",
    couvert : false,
    departement : 31,
    id : "176",
    id_secteur : "7",
    latitude : "43.78243",
    longitude : "1.19638",
    nom : "Saint Cezert",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Saint Cezert"
  }, {
    "abbrev" : "SAINT-FELIX",
    adresse : "Place du Village - derrière le Château",
    couvert : false,
    departement : 31,
    id : "177",
    id_secteur : "8",
    latitude : "43.44853",
    longitude : "1.89005",
    nom : "Saint Felix Lauragais",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Saint Felix Lauragais"
  }, {
    "abbrev" : "Saint-Gaudens PSG",
    couvert : true,
    departement : 31,
    id : "180",
    id_secteur : "3",
    latitude : "43.12018",
    longitude : "0.72864",
    nom : "Saint Gaudens PSG",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Saint Gaudens"
  }, {
    couvert : true,
    departement : 31,
    id : "179",
    id_secteur : "3",
    latitude : "43.12018",
    longitude : "0.72864",
    nom : "Saint Gaudens CSP",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Saint Gaudens"
  }, {
    couvert : true,
    departement : 31,
    id : "178",
    id_secteur : "3",
    latitude : "43.12018",
    longitude : "0.72864",
    nom : "Saint Gaudens ABC",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Saint Gaudens"
  }, {
    "abbrev" : "SAINT-GENIES",
    couvert : false,
    departement : 31,
    id : "181",
    id_secteur : "4",
    latitude : "43.68248",
    longitude : "1.48557",
    nom : "Saint Genies Bellevue",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Saint Genies Bellevue"
  }, {
    "abbrev" : "SAINT-HILAIRE",
    adresse : "La plaine Sportive",
    couvert : false,
    departement : 31,
    id : "182",
    id_secteur : "6",
    latitude : "43.42286",
    longitude : "1.27936",
    nom : "Saint Hilaire",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Saint Hilaire"
  }, {
    "abbrev" : "SAINT-JEAN",
    couvert : false,
    departement : 31,
    id : "183",
    id_secteur : "4",
    latitude : "43.66915",
    longitude : "1.50381",
    nom : "Saint Jeannaise",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Saint Jean"
  }, {
    couvert : false,
    departement : 31,
    id : "184",
    id_secteur : "4",
    latitude : "43.74074",
    longitude : "1.36888",
    nom : "Saint Jory",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Saint Jory"
  }, {
    "abbrev" : "SAINT-JULIEN",
    adresse : "Stade - Route de Cazères",
    couvert : false,
    departement : 31,
    id : "185",
    id_secteur : "1",
    latitude : "43.24426",
    longitude : "1.15314",
    nom : "AB Saint-Julien",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Saint Julien Sur Garonne"
  }, {
    "abbrev" : "Saint-Leon",
    adresse : "Place Saint Roch",
    couvert : false,
    departement : 31,
    id : "186",
    id_secteur : "8",
    latitude : "43.39932",
    longitude : "1.56231",
    nom : "Saint Leon",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Saint Leon"
  }, {
    "abbrev" : "SAINT-LOUP-CAMMAS",
    couvert : false,
    departement : 31,
    id : "187",
    id_secteur : "4",
    latitude : "43.69686",
    longitude : "1.48005",
    nom : "Saint Loup",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Saint Loup Cammas"
  }, {
    "abbrev" : "SAINT-LYS",
    couvert : false,
    departement : 31,
    id : "188",
    id_secteur : "5",
    latitude : "43.51529",
    longitude : "1.17592",
    nom : "Saint Lys",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Saint Lys"
  }, {
    couvert : false,
    departement : 31,
    id : "189",
    id_secteur : "3",
    latitude : "43.19741",
    longitude : "0.73921",
    nom : "Saint Marcet",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Saint Marcet"
  }, {
    "abbrev" : "SAINT-MARTORY",
    couvert : false,
    departement : 31,
    id : "190",
    id_secteur : "3",
    latitude : "43.142",
    longitude : "0.92895",
    nom : "Saint Martory",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Saint Martory"
  }, {
    "abbrev" : "SAINT-ORENS",
    adresse : "Chemin de Montfalcou",
    couvert : true,
    departement : 31,
    id : "191",
    id_secteur : "8",
    latitude : "43.57474",
    longitude : "1.51499",
    nom : "Saint Orens",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Saint Orens De Gameville"
  }, {
    adresse : "Place de la Mairie",
    couvert : false,
    departement : 31,
    id : "192",
    id_secteur : "8",
    latitude : "43.56943",
    longitude : "1.62727",
    nom : "Saint Pierre De Lages",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Saint Pierre De Lages"
  }, {
    "abbrev" : "ST SAUVEUR",
    couvert : false,
    departement : 31,
    id : "193",
    id_secteur : "4",
    latitude : "43.74728",
    longitude : "1.39931",
    nom : "Saint Sauveur",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Saint Sauveur"
  }, {
    "abbrev" : "SAINT-SULPICE",
    adresse : "Le Parc",
    couvert : false,
    departement : 31,
    id : "194",
    id_secteur : "1",
    latitude : "43.32945",
    longitude : "1.32359",
    nom : "Saint Sulpice Sur Leze",
    sect : "Car",
    secteur : "Carbonne",
    type : "Petanque",
    ville : "Saint Sulpice Sur Leze"
  }, {
    "abbrev" : "SAINT-THOMAS",
    couvert : false,
    departement : 31,
    id : "195",
    id_secteur : "5",
    latitude : "43.51427",
    longitude : "1.08202",
    nom : "Saint Thomas",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Saint Thomas"
  }, {
    "abbrev" : "STE-FOY-PEYROLIERES",
    couvert : false,
    departement : 31,
    id : "196",
    id_secteur : "5",
    latitude : "43.49667",
    longitude : "1.13768",
    nom : "Sainte Foy De Peyrolieres",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Sainte Foy De Peyrolieres"
  }, {
    "abbrev" : "Salies-Du-Salat",
    couvert : false,
    departement : 31,
    id : "197",
    id_secteur : "3",
    latitude : "43.10365",
    longitude : "0.96028",
    nom : "Salies Du Salat",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Salies Du Salat"
  }, {
    "abbrev" : "Salles-Et-Pratviel",
    couvert : false,
    departement : 31,
    id : "198",
    id_secteur : "3",
    latitude : "42.82901",
    longitude : "0.60502",
    nom : "Salles Et Pratviel",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Salles Et Pratviel"
  }, {
    couvert : false,
    departement : 31,
    id : "199",
    id_secteur : "4",
    latitude : "43.83678",
    longitude : "1.4637",
    nom : "Sayrac",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Sayrac (Villemur Sur Tarn)"
  }, {
    couvert : false,
    departement : 31,
    id : "200",
    id_secteur : "7",
    latitude : "43.69513",
    longitude : "1.35367",
    nom : "Seilh",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Seilh"
  }, {
    adresse : "10 passage des Ecoles",
    couvert : false,
    departement : 31,
    id : "201",
    id_secteur : "6",
    latitude : "43.49682",
    longitude : "1.31121",
    nom : "Seysses",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Seysses"
  }, {
    couvert : false,
    departement : 31,
    id : "202",
    id_secteur : "7",
    latitude : "43.71185",
    longitude : "1.1613",
    nom : "Thil",
    sect : "Gre",
    secteur : "Grenade",
    type : "Petanque",
    ville : "Thil"
  }, {
    adresse : "42 bis avenue de Rangueil 31400",
    couvert : false,
    departement : 31,
    id : "224",
    id_secteur : "2",
    latitude : "43.57562",
    longitude : "1.455",
    nom : "Leon Viala",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "Place Marius Pinel 31500",
    couvert : false,
    departement : 31,
    id : "231",
    id_secteur : "2",
    latitude : "43.60237",
    longitude : "1.46704",
    nom : "Pinel PC",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "25 rue de Périole - Parc Michelet",
    couvert : false,
    departement : 31,
    id : "206",
    id_secteur : "2",
    latitude : "43.61566",
    longitude : "1.45515",
    nom : "Bonnefoy Raynal",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "118 Rue de Périole",
    couvert : false,
    departement : 31,
    id : "238",
    id_secteur : "2",
    latitude : "43.6175",
    longitude : "1.46266",
    nom : "Rex PC",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "119 rue des Amidonniers 31000",
    couvert : false,
    departement : 31,
    id : "245",
    id_secteur : "2",
    latitude : "43.60923",
    longitude : "1.41527",
    nom : "Tracassin",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    couvert : false,
    departement : 31,
    id : "213",
    id_secteur : "2",
    latitude : "43.59686",
    longitude : "1.43662",
    nom : "Cours Dillon",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "rue de l'Ukraine 31100",
    couvert : false,
    departement : 31,
    id : "220",
    id_secteur : "2",
    latitude : "43.57877",
    longitude : "1.41602",
    nom : "La Farouette",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "Rue du Béarn 31100",
    couvert : false,
    departement : 31,
    id : "227",
    id_secteur : "2",
    latitude : "43.57604",
    longitude : "1.4115",
    nom : "Papus PC",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    "abbrev" : "RAMIERS (GIRONIS)",
    adresse : "Parc du Gironis - Ch du Chapitre",
    couvert : false,
    departement : 31,
    id : "234",
    id_secteur : "2",
    latitude : "43.5624",
    longitude : "1.41399",
    nom : "Ramiers",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "Rue Raphael (Georges Rigal) 31200",
    couvert : false,
    departement : 31,
    id : "209",
    id_secteur : "2",
    latitude : "43.64174",
    longitude : "1.44195",
    nom : "Boules Raphael Parc",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    "abbrev" : "S.O.BONNEFOY",
    adresse : "Boulodrome 6 rue de archives",
    couvert : false,
    departement : 31,
    id : "241",
    id_secteur : "2",
    latitude : "43.62378",
    longitude : "1.46074",
    nom : "SO Bonnefoy",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "5 rue d'Aix",
    couvert : false,
    departement : 31,
    id : "216",
    id_secteur : "2",
    latitude : "43.57788",
    longitude : "1.43772",
    nom : "Empalot",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "Place Sauvegrain",
    couvert : false,
    departement : 31,
    id : "223",
    id_secteur : "2",
    latitude : "43.5898",
    longitude : "1.37796",
    nom : "Lardenne PC",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    "abbrev" : "HERACLES",
    adresse : "Square Heracles Av Paul Séjourné 31100",
    couvert : false,
    departement : 31,
    id : "230",
    id_secteur : "2",
    latitude : "43.60786",
    longitude : "1.42787",
    nom : "Petanque Heracles",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "27 rue Jeanne Marvig 31400",
    couvert : false,
    departement : 31,
    id : "205",
    id_secteur : "2",
    latitude : "43.57822",
    longitude : "1.46381",
    nom : "Boule D'Argent Rangeuil",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "Place André D'Aste",
    couvert : false,
    departement : 31,
    id : "237",
    id_secteur : "2",
    latitude : "43.58285",
    longitude : "1.4408",
    nom : "Recollets D'Aste",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "42 Avenue Frédéric Estèbe 31200",
    couvert : true,
    departement : 31,
    id : "244",
    id_secteur : "2",
    latitude : "43.62127",
    longitude : "1.43735",
    nom : "TPO",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "8 rue des Gongous",
    couvert : false,
    departement : 31,
    id : "212",
    id_secteur : "2",
    latitude : "43.60849",
    longitude : "1.45987",
    nom : "Colonne Marengo",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    "abbrev" : "Boule D'or St-Simon",
    adresse : "18 rue du cimetière",
    couvert : false,
    departement : 31,
    id : "219",
    id_secteur : "2",
    latitude : "43.57877",
    longitude : "1.41602",
    nom : "La Boule D'Or",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    "abbrev" : "NBCBP-Bagatelle",
    adresse : "52 rue du Lot 31100",
    couvert : false,
    departement : 31,
    id : "226",
    id_secteur : "2",
    latitude : "43.58143",
    longitude : "1.40855",
    nom : "NBCBP",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    "abbrev" : "Pradettes",
    adresse : "12 rue Ferdinand de Lesseps",
    couvert : false,
    departement : 31,
    id : "233",
    id_secteur : "2",
    latitude : "43.57887",
    longitude : "1.38304",
    nom : "Pradettes",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "13 rue des Chamois 31200",
    couvert : true,
    departement : 31,
    id : "208",
    id_secteur : "2",
    latitude : "43.63912",
    longitude : "1.44206",
    nom : "Boules Izards Club",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "Rue des Cormorans 31400",
    couvert : false,
    departement : 31,
    id : "240",
    id_secteur : "2",
    latitude : "43.57604",
    longitude : "1.43794",
    nom : "Ronde D'Empalot",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    "abbrev" : "LA DIGUE",
    adresse : "2 rue Laganne",
    couvert : false,
    departement : 31,
    id : "215",
    id_secteur : "2",
    latitude : "43.59686",
    longitude : "1.43662",
    nom : "Digue Fer A Cheval",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "25 chemin Lapujade",
    couvert : false,
    departement : 31,
    id : "222",
    id_secteur : "2",
    latitude : "43.61823",
    longitude : "1.45255",
    nom : "Lapujade",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "33 rue René Fonquerne 31200",
    couvert : false,
    departement : 31,
    id : "229",
    id_secteur : "2",
    latitude : "43.627",
    longitude : "1.42793",
    nom : "Petanque Fonquerne",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "28 Allée de la Limagne",
    couvert : false,
    departement : 31,
    id : "204",
    id_secteur : "2",
    latitude : "43.61974",
    longitude : "1.40058",
    nom : "Ancely",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    "abbrev" : "RASPAIL-CÔTE PAVEE",
    adresse : "256 Avenue Jean Rieux 31500",
    couvert : false,
    departement : 31,
    id : "236",
    id_secteur : "2",
    latitude : "43.58361",
    longitude : "1.47786",
    nom : "Raspail Cote Pavee",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "imp du Ramier des catalans",
    couvert : false,
    departement : 31,
    id : "243",
    id_secteur : "2",
    latitude : "43.60582",
    longitude : "1.42198",
    nom : "TEC",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "6 Place Baudin 31300",
    couvert : false,
    departement : 31,
    id : "211",
    id_secteur : "2",
    latitude : "43.60473",
    longitude : "1.40947",
    nom : "Casselardit",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "19 rue Képier 31500",
    couvert : false,
    departement : 31,
    id : "218",
    id_secteur : "2",
    latitude : "43.61242",
    longitude : "1.46365",
    nom : "Jolimont",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "Boul. Michel Colomba Rue Laulanie 31100",
    couvert : false,
    departement : 31,
    id : "225",
    id_secteur : "2",
    latitude : "43.58011",
    longitude : "1.40108",
    nom : "Lou Bosc PC",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    "abbrev" : "Pont Des Demoiselles",
    adresse : "Place Roger Arnaud",
    couvert : false,
    departement : 31,
    id : "232",
    id_secteur : "2",
    latitude : "43.58723",
    longitude : "1.46315",
    nom : "Pont Demoiselles",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    "abbrev" : "La Boule Du Rugby",
    adresse : "152 Bis Avenue des Minimes 31200",
    couvert : false,
    departement : 31,
    id : "207",
    id_secteur : "2",
    latitude : "43.62494",
    longitude : "1.4344",
    nom : "Boule Du Rugby",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "9 rue de Gascogne 31300",
    couvert : false,
    departement : 31,
    id : "239",
    id_secteur : "2",
    latitude : "43.59635",
    longitude : "1.42715",
    nom : "Roguet",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    "abbrev" : "Croix-Daurade",
    adresse : "5 rue Francis Lopez 31200",
    couvert : true,
    departement : 31,
    id : "214",
    id_secteur : "2",
    latitude : "43.63622",
    longitude : "1.46304",
    nom : "Croix Daurade",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "imp Eugene Trutat",
    couvert : false,
    departement : 31,
    id : "221",
    id_secteur : "2",
    latitude : "43.58334",
    longitude : "1.48513",
    nom : "La Terrasse",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "6 rue de caillou gris 31200",
    couvert : false,
    departement : 31,
    id : "228",
    id_secteur : "2",
    latitude : "43.62026",
    longitude : "1.43473",
    nom : "Petanque Club Le Cochonnet",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "12 rue d'Arles",
    couvert : false,
    departement : 31,
    id : "203",
    id_secteur : "2",
    latitude : "43.62891",
    longitude : "1.46776",
    nom : "Amouroux",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "62 rue de Nîmes",
    couvert : false,
    departement : 31,
    id : "235",
    id_secteur : "2",
    latitude : "43.57487",
    longitude : "1.46575",
    nom : "Rangeuil",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "44 rue Louis Plana 31500",
    couvert : false,
    departement : 31,
    id : "242",
    id_secteur : "2",
    latitude : "43.61061",
    longitude : "1.47946",
    nom : "Soupetard",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "8 rue Ernest DUFIN",
    couvert : false,
    departement : 31,
    id : "210",
    id_secteur : "2",
    latitude : "43.59927",
    longitude : "1.40095",
    nom : "CAF Petanque",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    adresse : "Allées Frédéric Mistral 31000",
    couvert : false,
    departement : 31,
    id : "217",
    id_secteur : "2",
    latitude : "43.59499",
    longitude : "1.45275",
    nom : "Grand Rond",
    sect : "Tlse",
    secteur : "Toulouse",
    type : "Petanque",
    ville : "Toulouse"
  }, {
    couvert : true,
    departement : 31,
    id : "246",
    id_secteur : "5",
    latitude : "43.581",
    longitude : "1.34672",
    nom : "Tournefeuille",
    sect : "Pib",
    secteur : "Pibrac",
    type : "Petanque",
    ville : "Tournefeuille"
  }, {
    couvert : false,
    departement : 31,
    id : "247",
    id_secteur : "8",
    latitude : "43.4768",
    longitude : "1.74484",
    nom : "Toutens",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Toutens"
  }, {
    adresse : "Au Village",
    couvert : false,
    departement : 31,
    id : "248",
    id_secteur : "8",
    latitude : "43.42415",
    longitude : "1.75453",
    nom : "Vallegue",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Vallegue"
  }, {
    adresse : "Allee du Duc de Ventadour",
    couvert : false,
    departement : 31,
    id : "249",
    id_secteur : "8",
    latitude : "43.43312",
    longitude : "1.44096",
    nom : "Venerque / Le Vernet",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Venerque"
  }, {
    couvert : false,
    departement : 31,
    id : "250",
    id_secteur : "4",
    latitude : "43.6575",
    longitude : "1.6603",
    nom : "Verfeil",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Verfeil"
  }, {
    couvert : false,
    departement : 31,
    id : "251",
    id_secteur : "4",
    latitude : "43.75161",
    longitude : "1.49122",
    nom : "Villaries",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Villaries"
  }, {
    couvert : false,
    departement : 31,
    id : "252",
    id_secteur : "4",
    latitude : "43.83019",
    longitude : "1.43034",
    nom : "CB Villaudricain",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Villaudric"
  }, {
    "abbrev" : "VILLEFRANCHE",
    couvert : false,
    departement : 31,
    id : "253",
    id_secteur : "8",
    latitude : "43.39891",
    longitude : "1.71834",
    nom : "Villefranche De Lauragais",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Villefranche De Lauragais"
  }, {
    couvert : false,
    departement : 31,
    id : "254",
    id_secteur : "4",
    latitude : "43.82862",
    longitude : "1.50952",
    nom : "Villematier",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Villematier"
  }, {
    couvert : false,
    departement : 31,
    id : "255",
    id_secteur : "4",
    latitude : "43.85627",
    longitude : "1.50507",
    nom : "Villemur",
    sect : "4Val",
    secteur : "4 Vallees",
    type : "Petanque",
    ville : "Villemur Sur Tarn"
  }, {
    couvert : false,
    departement : 31,
    id : "256",
    id_secteur : "3",
    latitude : "43.12063",
    longitude : "0.66567",
    nom : "Villeneuve De Riviere",
    sect : "Com",
    secteur : "Comminges",
    type : "Petanque",
    ville : "Villeneuve De Riviere"
  }, {
    "abbrev" : "Villeneuve-Tolosane",
    adresse : " 1 chemin du Caminas",
    couvert : true,
    departement : 31,
    id : "257",
    id_secteur : "6",
    latitude : "43.52191",
    longitude : "1.34282",
    nom : "Villeneuve Tolosane",
    sect : "Mur",
    secteur : "Muret",
    type : "Petanque",
    ville : "Villeneuve Tolosane"
  }, {
    adresse : "Place des Tilleuls",
    couvert : false,
    id : "258",
    id_secteur : "8",
    latitude : "43.43563",
    longitude : "1.66253",
    nom : "Villenouvelle",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Villenouvelle"
  } ];

  markers_: Array<Object> = [{
    adresse : "Boulodrome Municipal",
    couvert : false,
    departement : 31,
    id : "1",
    id_secteur : "8",
    latitude : 43.32077,
    longitude : 1.5895,
    nbTerrains : 10,
    nom : "Aignes",
    sect : "Gls",
    secteur : "Grand Lauragais",
    type : "Petanque",
    ville : "Aignes"
  }];
  @ViewChild('myMap') myMap: any;

  doThis(elem){

    elem.latitude = parseFloat(elem.latitude);
    elem.longitude = parseFloat(elem.longitude);
    return elem;
  }
  constructor(af: AngularFire) {
    this.boulodromes = af.database.list('/boulodromes');

    this.boulodromes
      .subscribe(bou => {
        bou.map(this.doThis);
        console.log(bou);
        this.markers = bou;
    })

  }


  modifBoulodrome(boulodrome){
    this.boulodromeIsSelected = true;
    this.index = boulodrome.$key;
    this.title = boulodrome.nom;
    this.ville = boulodrome.ville;
    this.departement = boulodrome.departement;
    this.secteur = boulodrome.secteur;
    this.type = boulodrome.type;
    this.adresse = boulodrome.adresse;
    this.latitude = boulodrome.latitude;
    this.longitude = boulodrome.longitude;
    this.nbTerrains = (boulodrome.nbTerrains !== undefined ? boulodrome.nbTerrains : null);
    this.couvert = boulodrome.couvert;
  }

  saveBoulodrome(){
    let myBoulodrome = {
      nom: this.title,
      ville: this.ville,
      departement: this.departement,
      secteur: this.secteur,
      adresse:this.adresse,
      latitude: this.latitude,
      longitude: this.longitude,
      nbTerrains: this.nbTerrains,
      couvert: this.couvert
    };
    console.log(this);
    let key = this.index;
    this.boulodromes.update(key, myBoulodrome);
  }

  ngOnInit() {

  }

  ngAfterViewInit() {

    this.showMap = true;


  }

}
